# Generated by Django 3.1.7 on 2021-02-22 18:21

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210222_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Секция о нас',
            },
        ),
        migrations.CreateModel(
            name='FirstServiceSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок первого блока сервисов')),
                ('description', models.TextField(verbose_name='Описание первого блока сервиса')),
            ],
            options={
                'verbose_name': 'Первый блок сервиса',
            },
        ),
        migrations.CreateModel(
            name='SecondServiceSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок второго блока сервисов')),
                ('description', models.TextField(verbose_name='Описание второго блока сервиса')),
            ],
            options={
                'verbose_name': 'Второй блок сервиса',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Фио участника команды')),
                ('description', models.TextField(verbose_name='Пару слов об участнике')),
                ('image', models.ImageField(upload_to='team_members', verbose_name='Фото участника')),
            ],
            options={
                'verbose_name': 'Участник команды',
                'verbose_name_plural': 'Участники команды',
            },
        ),
        migrations.CreateModel(
            name='ThirdServiceSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок третьего блока сервисов')),
                ('description', models.TextField(verbose_name='Описание третьего блока сервиса')),
            ],
            options={
                'verbose_name': 'Третий блок сервиса',
            },
        ),
        migrations.CreateModel(
            name='Service3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок сервиса3')),
                ('description', models.CharField(max_length=255, verbose_name='Описание сервиса3')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_services', to='main.thirdservicesection')),
            ],
            options={
                'verbose_name': 'Сервис3',
                'verbose_name_plural': 'Сервисы3',
            },
        ),
        migrations.CreateModel(
            name='Service2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок сервиса2')),
                ('description', models.TextField(verbose_name='Описание сервиса2')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_services', to='main.secondservicesection')),
            ],
            options={
                'verbose_name': 'Сервис2',
                'verbose_name_plural': 'Сервисы2',
            },
        ),
        migrations.CreateModel(
            name='Service1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок сервиса1')),
                ('description', models.TextField(verbose_name='Описание сервиса1')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_services', to='main.firstservicesection')),
            ],
            options={
                'verbose_name': 'Сервис1',
                'verbose_name_plural': 'Сервисы1',
            },
        ),
    ]
