# Generated by Django 3.1.7 on 2021-02-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_aboutus_firstservicesection_secondservicesection_service1_service2_service3_teammember_thirdservices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firstservicesection',
            options={'verbose_name': 'Первый блок сервиса', 'verbose_name_plural': 'Первый блок сервиса'},
        ),
        migrations.AlterModelOptions(
            name='secondservicesection',
            options={'verbose_name': 'Второй блок сервиса', 'verbose_name_plural': 'Второй блок сервиса'},
        ),
        migrations.AlterModelOptions(
            name='thirdservicesection',
            options={'verbose_name': 'Третий блок сервиса', 'verbose_name_plural': 'Третий блок сервиса'},
        ),
        migrations.AddField(
            model_name='service1',
            name='image',
            field=models.ImageField(default=0, upload_to='service_images', verbose_name='Изоброжение сервиса1'),
            preserve_default=False,
        ),
    ]
