# Generated by Django 3.1.7 on 2021-02-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210222_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='service2',
            name='icon',
            field=models.ImageField(default=0, upload_to='service_images', verbose_name='Иконка сервиса2'),
            preserve_default=False,
        ),
    ]
