# Generated by Django 3.1.7 on 2021-02-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_service2_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service3',
            name='description',
            field=models.TextField(verbose_name='Описание сервиса3'),
        ),
    ]
