# Generated by Django 3.1.7 on 2021-02-22 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210222_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='FourthServiceSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок четвёртого блока сервисов')),
                ('image', models.ImageField(upload_to='bc_images', verbose_name='Задний фон четвёртого блока сервисов')),
                ('description', models.TextField(verbose_name='Описание четвёртого блока сервиса')),
            ],
            options={
                'verbose_name': 'Четвёртый блок сервиса',
                'verbose_name_plural': 'Четвёртый блок сервиса',
            },
        ),
        migrations.AddField(
            model_name='secondservicesection',
            name='image',
            field=models.ImageField(default=0, upload_to='bc_images', verbose_name='Задний фон второго блока сервисов'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Service4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='service_images', verbose_name='Иконка сервиса4')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок сервиса4')),
                ('number', models.CharField(max_length=255, verbose_name='Номер сервиса4')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_services', to='main.fourthservicesection')),
            ],
            options={
                'verbose_name': 'Сервис4',
                'verbose_name_plural': 'Сервисы4',
            },
        ),
    ]
