# Generated by Django 3.1.7 on 2021-02-22 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210222_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='FifthServiceSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок пятого блока сервисов')),
                ('description', models.TextField(verbose_name='Описание пятого блока сервиса')),
            ],
            options={
                'verbose_name': 'Пятый блок сервиса',
                'verbose_name_plural': 'Пятый блок сервиса',
            },
        ),
        migrations.CreateModel(
            name='Service5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок сервиса5')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_services', to='main.fifthservicesection')),
            ],
            options={
                'verbose_name': 'Сервис5',
                'verbose_name_plural': 'Сервисы5',
            },
        ),
    ]
