# Generated by Django 3.1.7 on 2021-02-24 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_fifthservicesection_service5'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Страница предложений',
                'verbose_name_plural': 'Страница предложений',
            },
        ),
        migrations.AlterField(
            model_name='service1',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='main.firstservicesection'),
        ),
        migrations.AlterField(
            model_name='service2',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='main.secondservicesection'),
        ),
        migrations.AlterField(
            model_name='service3',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='main.thirdservicesection'),
        ),
        migrations.AlterField(
            model_name='service4',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='main.fourthservicesection'),
        ),
        migrations.AlterField(
            model_name='service5',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='main.fifthservicesection'),
        ),
        migrations.AddField(
            model_name='offer',
            name='section',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='main.offersection'),
            preserve_default=False,
        ),
    ]
