# Generated by Django 3.1.7 on 2021-02-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210224_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Начало главной страницы',
                'verbose_name_plural': 'Начало главной страницы',
            },
        ),
    ]
