# Generated by Django 3.1.7 on 2021-02-25 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_mainpagesection'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurTeamSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Секция наша команда',
                'verbose_name_plural': 'Секция наша команда',
            },
        ),
        migrations.AddField(
            model_name='teammember',
            name='section',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='main.ourteamsection'),
            preserve_default=False,
        ),
    ]
