# Generated by Django 3.1.7 on 2021-02-25 20:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_language_languagessection'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurProjectsSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Секция "Наши проекты"',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='eventorganizationsection',
            options={'verbose_name': 'Секция организации мероприятий', 'verbose_name_plural': 'Секция организации мероприятий'},
        ),
    ]
