# Generated by Django 3.1.7 on 2021-02-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210225_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourprojectssection',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
