# Generated by Django 3.1.7 on 2021-03-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210313_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languageservice',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название услуги'),
        ),
    ]
