# Generated by Django 3.1.7 on 2021-04-17 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210313_2020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offersection',
            options={'verbose_name': 'Секция предложений', 'verbose_name_plural': 'Секция предложений'},
        ),
    ]
