# Generated by Django 3.1.7 on 2021-02-22 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('created_at', models.DateField(verbose_name='Дата создания поста')),
                ('description', models.TextField(verbose_name='Описание поста')),
            ],
            options={
                'verbose_name': 'Пост из блога',
                'verbose_name_plural': 'Посты из блога',
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='made_on',
            field=models.DateField(verbose_name='Был осущетвлен в'),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок фото (нужно для сео)')),
                ('file', models.ImageField(upload_to='blog_images', verbose_name='Фото поста')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_images', to='secondary.post')),
            ],
            options={
                'verbose_name': 'Изоброжение поста',
                'verbose_name_plural': 'Изоброжения постов',
            },
        ),
    ]
