# Generated by Django 3.1.7 on 2021-02-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0002_auto_20210222_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioproject',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Показывать на главной странице'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Показывать на главной странице'),
        ),
    ]
