# Generated by Django 3.1.7 on 2021-03-02 05:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0004_auto_20210301_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioproject',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Описание поста'),
        ),
    ]
