# Generated by Django 3.1.7 on 2021-03-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0005_auto_20210302_0559'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=255, verbose_name='ФИО Отправителя')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email отправителя')),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер отправителя')),
                ('message', models.TextField(verbose_name='Сообщение отправителя')),
            ],
            options={
                'verbose_name': 'Сообщение клиента',
                'verbose_name_plural': 'Сообщения клиентов',
            },
        ),
    ]
