# Generated by Django 3.1.7 on 2021-04-17 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0007_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
